### ISSUE TITLE
 File is not listed within the file list of project '.../__typetests__/tsconfig.json'

### ISSUE THREAD

**Issue by dac09** [jest-community/jest-runner-tsd#111]
I seem to have an odd configuration issue with the tsd runner. I have a file where I define the types I'm using in my tsd test, but I receive this error when running tsd tests. There are no TS errors while running `tsc`, only while running the jest-runner-tsd.

It's just a type import:

```ts
import type { RouteParams, ParamType } from '../routeParamsTypes'
```

```shell
 File '/Users/dac09/Code/redwood/packages/router/src/routeParamsTypes.ts' is not listed within the file list of project '/Users/dac09/Code/redwood/packages/router/src/__typetests__/tsconfig.json'
```
---

### Folder structure
The relevant parts of the tree looks like this:
```
.
├── ambient.d.ts
├── jest.config.js
├── jest.setup.js
├── package.json
├── src
│   ├── __tests__
│   │   ├── 
│   ├── __typetests__
│   │   ├── routeParamsTypes.test.ts
│   │   └── tsconfig.json
│   ├── routeParamsTypes.ts
└── tsconfig.json
```

### Jest config
```js
/** @type {import('@jest/types').Config.InitialOptions} */
module.exports = {
  projects: [
    {
      displayName: 'code',
      setupFilesAfterEnv: ['./jest.setup.js'],
      testEnvironment: 'jest-environment-jsdom',
      testMatch: ['**/*.test.+(ts|tsx|js)', '!**/__typetests__/*.ts'],
    },
    {
      displayName: {
        color: 'blue',
        name: 'types',
      },
      runner: 'jest-runner-tsd',
      testMatch: ['**/__typetests__/*.test.ts'],
    },
  ],
}

```

### Debugging
Just to be sure, I've defined a tsconfig.json in the `__typetests__` folder too that just extends the original. 

```json
{
  "extends": "../../tsconfig.json"
}
```

The output of `yarn tsc -p src/__typetests__ --showConfig` lists routeParamsTypes.ts correctly.

---
**Other Workarounds I've tried**
1. Renaming to a `.d.ts` file seems to work, but.... then I'll need to modify my build step to manually copy over the .d.ts file into the dist folder 
2. I can import the type from the "built" package. - but that requires the package to be built before running the test, which is not ideal!

Would appreciate any tips, and thanks for putting this together.

**Comment by dac09** [comment]
No excludes in the `tsconfig.json`:

```
{
  "extends": "../../tsconfig.compilerOption.json",
  "compilerOptions": {
    "tsBuildInfoFile": "dist/tsconfig.tsbuildinfo",
    "baseUrl": ".",
    "rootDir": "src",
    "outDir": "dist",
    "paths": {
      "src/*": ["./src/*"]
    }
  },
  "include": ["src", "./ambient.d.ts"],
  "references": [
    { "path": "../auth" },
  ]
}
```

All the code sits here if you wanted to take a deeper look: https://github.com/redwoodjs/redwood/pull/6364/files

(note that in the PR, I'm importing from the package root to avoid this error)

**Comment by mrazauskas** [comment]
Thanks for the link. I will take a look.

**Comment by mrazauskas** [comment]
Just to leave a note, adding `"compilerOptions": {"composite": false}` to `__typetests__/tsconfig.json` fixed everything. See https://github.com/redwoodjs/redwood/pull/6364#discussion_r968435434

**Comment by dac09** [comment]
Closing, thanks to @mrazauskas for the help! 

For anyone coming across this bug:

1. Make sure `compilerOptions.composite` is explicitly set to false in your `__typetests__/tsconfig.json`. This is particularly important to check, if you are inheriting your tsconfig from another file further up the repo (such as in monorepos, or your current project's tsconfig)
2. You may need to tweak other settings as well, in my case:
```
  "compilerOptions": {
    "composite": false, // 👈 couldn't set composite to false without changing these other values too. TS in vscode will highlight the error
    "incremental": true,
    "declaration": false,
    "declarationMap": false,
    "emitDeclarationOnly": false
  },
```

**Comment by mrazauskas** [comment]
@SimenB Thanks for the Member badge. This look fun ;D
