### ISSUE TITLE
Could not find test files. Create one and try again

### ISSUE THREAD

**Issue by crutchcorn** [jest-community/jest-runner-tsd#39]
When trying to run tests, I get the following error:

```
FAIL  src/__type_tests__/pick-deep.test-d.ts
  ● Test suite failed to run

    Could not find test files. Create one and try again
```

It seems like there isn't anything being found from `mlh-tsd` in `findCustomTestFiles`. If, after `globby`, I output:

```
    console.log({testFilesPattern, testFiles, cwd})
```

I get this:

```
{
  testFilesPattern: [
    'C:\\Users\\crutchcorn\\git\\UnicornUtter\\ts-util-helpers\\src\\__type_tests__\\pick-deep.test-d.ts'
  ],
  testFiles: [],
  cwd: 'C:\\Users\\crutchcorn\\git\\UnicornUtter\\ts-util-helpers'
}
```

My jest file is this:

```
module.exports = {
    runner: 'jest-runner-tsd',
    testMatch: ['**/*.test-d.ts'],
};
```

And my test is indeed in the pick-deep.test-d.ts path

I'm running Windows 11 if that helps

**Comment by mrazauskas** [comment]
Thanks for report.

Most probably all got fixed in #19. I was wrestling with this error on CI. Here is the problematic line (`testFiles` must be globs, so slashes had to be normalised): https://github.com/jest-community/jest-runner-tsd/blob/82e6f91f9225a3ec08c3571a144f5d0749e1ee02/src/run.js#L44

Updated code is not yet released.

You can patch the library inside `node_modules` to see if that helps. Or we could ask @SimenB for a release (;

**Comment by SimenB** [comment]
https://github.com/jest-community/jest-runner-tsd/releases/tag/v1.2.0

**Comment by crutchcorn** [comment]
That was fast! Thanks y'all!

Don't wanna open a new issue in case this is my fault for not noticing first. Is passing a project to `tsd` supported in the runner?

Something like this:

https://github.com/SamVerschueren/tsd/issues/32#issuecomment-778650556

**Comment by mrazauskas** [comment]
Not sure I fully understand your question. Do you try to find out if the workaround will work? It should work. The runner is just a tiny wrapper around `tsd`.

If something does not work, better open new issue (;

**Comment by crutchcorn** [comment]
Well, I'm admittedly not sure where to pass the second argument for said workaround 😅 (the project name) in the test runner

**Comment by mrazauskas** [comment]
Ah.. That’s more simple with the runner. There is no need to create a dummy project. Just point to an empty `.d.ts` file using a docblock at the top of your test file.

See [docs](https://github.com/jest-community/jest-runner-tsd#docblocks) and [example](https://github.com/jest-community/jest-runner-tsd/tree/main/e2e/__fixtures__/docblock) (that’s not empty `.d.ts`, but it should work with empty one too).

Does this help?

**Comment by crutchcorn** [comment]
Oh! I read that in the docs but didn't make the connection that the two were the same. Apologies!

**Comment by mrazauskas** [comment]
@crutchcorn Version 2.0.0 is just release. It does not require any work arounds (no more docblock, etc). Just go through the readme carefully. Many details changed.

Give it a try (;
